### ISSUE TITLE
내가 참여중인 경매조회 구현

### ISSUE THREAD

**Issue by SeunginYang** [DdangDdang5/Backend#10]
## 설명
내가 참여중인 경매조회 구현

## 기능구현 목록
- [ ] Get방식으로 유저가 현재 참여중인 경매 목록을 조회가능하게 하고자 함
- [ ] "시작가, 현재가, 경매기간, 카테고리, 지역, 거래방법 등 속성 추가

**Comment by pmjn1025** [comment]
프런트와 최종 확인했습니다.
