### ISSUE TITLE
경매 통합구분 조회 구현(카테고리, 지역)

### ISSUE THREAD

**Issue by SeunginYang** [DdangDdang5/Backend#25]
## 설명
경매 통합구분 조회 구현(카테고리, 지역)

## 기능구현 목록
- [ ] 경매 게시글에 등록 된 "카테고리 및 지역"을 조회하여 전체 경매 게시글 중 "카테고리 및 지역"에 해당되는 경매 게시물을 Response함

**Comment by pmjn1025** [comment]
프런트와 최종 확인했습니다.
