### ISSUE TITLE
경매 참여 구현

### ISSUE THREAD

**Issue by SeunginYang** [DdangDdang5/Backend#26]
## 설명
경매 참여 구현

## 기능구현 목록
- [ ]  회원만 경매 참여 가능 구현
- [ ]  경매 참여 기능 구현 (경매 참여 접근 시 참여가능, 1번 더 경매 접근 시 경매 참여 취소 기능 구현)
- [ ]  경매 참여자 수 계산, 만약 참여자 "0명" 일 시 입찰자가 없습니다 / "1명" 이라도 있을 시 입찰자가 있습니다.

**Comment by pmjn1025** [comment]
프런트와 최종 확인했습니다.
