### ISSUE TITLE
경매 찜하기 구현

### ISSUE THREAD

**Issue by SeunginYang** [DdangDdang5/Backend#27]
## 설명
경매 찜하기 구현

## 기능구현 목록
- [ ] 경매 게시물에 관심이 있을 시 찜하기 할 수 있는 기능 구현 (찜하기 접근 시 찜하기 기능 / 1번 더 찜하기 접근 시 찜하기 취소 기능)

**Comment by pmjn1025** [comment]
프런트와 최종 확인했습니다.
