### ISSUE TITLE
경매 작성자 기준 찜하기 숫자 확인 하기 기능 구현

### ISSUE THREAD

**Issue by SeunginYang** [DdangDdang5/Backend#28]
## 설명
경매 작성자 기준 찜하기 숫자 확인 하기 기능 구현

## 기능구현 목록
- [ ] 경매자가 마이페이지에 접근 시 게시한 경매글에 대한 찜하기 숫자 확인기능 구현

**Comment by pmjn1025** [comment]
프런트와 최종 확인했습니다.
