### ISSUE TITLE
경매 카테고리 별 인기순 조회

### ISSUE THREAD

**Issue by SeunginYang** [DdangDdang5/Backend#29]
## 설명
경매 카테고리 별 인기순 조회

## 기능구현 목록
- [ ] 회원이 상세페이지에 접근 시 경매 게시글에 등록 된 카테고리 및  viewCnt+1를 카테고리 테이블에 저장, 
        각 회원들이 접근한 경매 게시글에 카테고리를 인기순으로 정렬, Response 기능 구현함.

**Comment by pmjn1025** [comment]
프런트와 최종 확인했습니다.
